---
- name: Install Git and Bootstrap Environment
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install git
      ansible.builtin.package:
        name: git
        state: present

    - name: Run bootstrap script
      ansible.builtin.shell:
        cmd: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/jjjahnke/chezmoi/main/bootstrap.sh)"
      become: yes
      become_user: jahnke
