---
- name: Install Git and Bootstrap Environment
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install git
      ansible.builtin.package:
        name: git
        state: present

    - name: Reboot the machine
      ansible.builtin.reboot:
        msg: "Rebooting machine after git installation"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami

    - name: Run bootstrap script
      ansible.builtin.shell:
        cmd: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/jjjahnke/chezmoi/main/bootstrap.sh)"
      become: yes
      become_user: jahnke
