---
- name: Install Git and Bootstrap Environment
  hosts: all
  become: yes
  vars_files:
    - vault_vars.yml
  tasks:
    - name: Check if git is installed
      ansible.builtin.shell: command -v git
      register: git_check
      ignore_errors: true
      changed_when: false

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_os_family == "Debian" and git_check.failed

    - name: Install git
      ansible.builtin.package:
        name: git
        state: present
      when: git_check.failed
      register: git_install_result

    - name: Ensure zsh is installed
      ansible.builtin.package:
        name: zsh
        state: present

    - name: Check current shell for jahnke
      ansible.builtin.shell: 'getent passwd jahnke | cut -d: -f7'
      register: current_shell
      changed_when: false

    - name: Set zsh as default shell for jahnke
      ansible.builtin.user:
        name: jahnke
        shell: /usr/bin/zsh
      when: current_shell.stdout != '/usr/bin/zsh'
      register: shell_change_result

    - name: Reboot the machine if needed
      ansible.builtin.reboot:
        msg: "Rebooting machine after installing git or changing shell"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami
      when: git_install_result.changed or shell_change_result.changed

    - name: Clone the repository
      ansible.builtin.git:
        repo: 'https://github.com/jjjahnke/chezmoi.git'
        dest: /tmp/chezmoi
        version: main
      become: yes
      become_user: jahnke

    - name: Run bootstrap script from local clone
      ansible.builtin.shell:
        cmd: /bin/bash /tmp/chezmoi/bootstrap.sh
      become: yes
      become_user: jahnke

    - name: Initialize chezmoi from local clone
      ansible.builtin.shell:
        cmd: chezmoi init --apply --source /tmp/chezmoi
      become: yes
      become_user: jahnke
      environment:
        PATH: "/home/jahnke/.local/bin:{{ ansible_env.PATH }}"
        VAULT_ADDR: "http://192.168.150.210:30200"
        VAULT_TOKEN: "{{ vault_token | trim }}"
